# port to serve on. metrics server is started on this port+1
port: 8080
logging:
  # enable debug logs
  debug: true

# pluggable backend: [nats]
backend:
  name: "nats"
  config:
    url: "0.0.0.0:4444"

# authentication options
authentication:
  # json web keys uri for authentication.
  # if empty, inbound jwt's will not be verified.
  jwks_uri: ""

# authorization options
authorization:
  requests: |
    package eventgate.authz.requests

    default allow = false

    allow {
      input.claims.sub = "1234567890"
      input.claims.name = "John Doe"
    }
  responses: |
    package eventgate.authz.responses

    default allow = true


