# port to serve on. metrics server is started on this port+1
port: 8820
# enable debug logs
debug: true
nats_url: "0.0.0.0:4444"
# json web keys uri for authentication
jwks_uri: ""
# rego policy for request authorization - this one allows any request
request_policy:
  rego_policy: |-
    package cloudEventsProxy.authz

    default allow = true
  # query the allow variable
  rego_query: "data.cloudEventsProxy.authz.allow"
# rego policy for response authorization - this one allows any request
response_policy:
  rego_policy: |-
    package cloudEventsProxy.authz

    default allow = true
  # query the allow variable
  rego_query: "data.cloudEventsProxy.authz.allow"


