# port to serve on. metrics server is started on this port+1 if enabled
port: 8080
# enable graphQL API
graphql: true
# enable rest API
rest: true
# enable metrics server
metrics: true
# enable grpcweb support
grpcweb: true
cors:
  allowed_origins:
    - "*"
  allowed_methods:
    - "POST"
    - "PUT"
    - "GET"
    - "OPTIONS"
  allowed_headers:
    - "*"
#tls:
#  cert_file: "/tmp/server.cert"
#  key_file: "/tmp/server.key"
logging:
  # enable debug logs
  debug: true

# pluggable backend: [inmem, redis, nats, stan]
backend:
  name: "inmem"

#backend:
#  name: "redis"
#  config:
#    addr: "0.0.0.0:6379"
#backend:
#  name: "nats"
#  config:
#    addr: "0.0.0.0:4444"
#backend:
#  name: "stan"
#  config:
#    addr: "0.0.0.0:4444"
#backend:
#  name: "stan"
#  config:
#    addr: "0.0.0.0:4444"

# authentication options
authentication:
  # json web keys uri for authentication.
  # if empty, inbound jwt's will not be verified.
  jwks_uri: ""

# authorization options
authorization:
  requests: |
    package eventgate.authz

    default allow = false

    allow {
      input.claims.sub = "1234567890"
      input.claims.name = "John Doe"
    }
  responses: |
    package eventgate.authz

    default allow = true


