# port to serve on. metrics server is started on this port+1
port: 8820
# enable debug logs
debug: true
# rego policy for authorization - this one allows any request
rego_policy: |-
  package cloudEventsProxy.authz

  default allow = true
# query the allow variable
rego_query: "data.cloudEventsProxy.authz.allow"
# json web keys uri for authentication
jwks_uri: ""
# add list of helm repos to load at startup
repos:
  - name: "stable"
    url: "https://charts.helm.sh/stable"