version: '3.7'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - default:/tmp/eventgate/mongo
    networks:
      default:
        aliases:
          - mongo
  nats:
    image: nats:latest
    ports:
      - "8222:8222"
      - "4222:4222"
    networks:
      default:
        aliases:
          - nats
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - default:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

networks:
  default:

volumes:
  default:
