version: '3.7'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - default:/tmp/stategate/mongo
    networks:
      default:
        aliases:
          - mongo
#  nats:
#    image: nats:latest
#    ports:
#      - "8222:8222"
#      - "4222:4222"
#    networks:
#      default:
#        aliases:
#          - nats
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      default:
        aliases:
          - redis
  stategate:
    image: colemanword/stategate:v0.2.3
    env_file:
      - ./.env
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      default:
        aliases:
          - stategate
networks:
  default:

volumes:
  default:
