version: '3.7'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - default:/tmp/stategate/mongo
    networks:
      default:
        aliases:
          - mongo
  nats:
    image: nats:latest
    ports:
      - "8222:8222"
      - "4222:4222"
    networks:
      default:
        aliases:
          - nats
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      default:
        aliases:
          - redis

networks:
  default:

volumes:
  default:
