apiVersion: v1
kind: Namespace
metadata:
  name: eventgate-system
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: eventgate-configmap
data:
  eventgate.yaml: |
    # port to serve on. metrics server is started on this port+1
    port: 8080
    # enable debug logs
    debug: true
    nats_url: "0.0.0.0:4444"
    # json web keys uri for authentication
    jwks_uri: ""
    # rego policy for request authorization - this one allows any request
    request_policy:
      rego_policy: |-
        package eventgate.authz

        default allow = true
      # query the allow variable
      rego_query: "data.eventgate.authz.allow"
    # rego policy for response authorization - this one allows any request
    response_policy:
      rego_policy: |-
        package eventgate.authz

        default allow = true
      # query the allow variable
      rego_query: "data.eventgate.authz.allow"

---
apiVersion: v1
kind: Service
metadata:
  name: eventgate-service
  namespace: eventgate-system
  labels:
    app: eventgate
spec:
  ports:
  - port: 8080
    name: api
  - port: 8081
    name: admin
  clusterIP: None
  selector:
    app: eventgate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventgate
  namespace: eventgate-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventgate
  template:
    metadata:
      labels:
        app: eventgate
    spec:
      serviceAccountName: eventgate-sa
      containers:
        - name: eventgate
          env:
            - name: EVENTGATE_CONFIG
              value: /tmp/eventgate.yaml
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          image: "colemanword/eventgate:v0.0.4"
          imagePullPolicy: Always
          ports:
          - containerPort: 8081
          - containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: "/tmp"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: eventgate-configmap

---
