apiVersion: v1
kind: Namespace
metadata:
  name: stategate-system
---

apiVersion: v1
kind: Service
metadata:
  name: stategate-service
  namespace: stategate-system
  labels:
    app: stategate
spec:
  ports:
  - port: 8080
    name: api
  - port: 8081
    name: metrics
  clusterIP: None
  selector:
    app: stategate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stategate
  namespace: stategate-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stategate
  template:
    metadata:
      labels:
        app: stategate
    spec:
      containers:
        - name: stategate
          env:
            # port to serve on. defaults to 8080
            - name: STATEGATE_PORT
              value: "8080"
            # enable debug logs (optional)
            - name: STATEGATE_DEBUG
              value: "true"
            # disable all authentication & authorization(jwks, request policies, response policies) (optional)
            - name: STATEGATE_AUTH_DISABLED
              value: "true"
#            # JSON Web Key Set remote URI used for fetching jwt signing keys for verification/validation (optional)
#            - name: STATEGATE_JWKS_URI
#              value: "https://www.googleapis.com/oauth2/v3/certs"
#            # OPA rego policy executed on inbound requests from clients
#            - name: STATEGATE_REQUEST_POLICY
#              value: "cGFja2FnZSBzdGF0ZWdhdGUuYXV0aHoKCmRlZmF1bHQgYWxsb3cgPSB0cnVl"
#            # OPA rego policy executed on responses sent to clients
#            - name: STATEGATE_RESPONSE_POLICY
#              value: "cGFja2FnZSBzdGF0ZWdhdGUuYXV0aHoKCmRlZmF1bHQgYWxsb3cgPSB0cnVl"
            # channel provider configuration(JSON) options: [redis, nats, imqp]
            # STATEGATE_CHANNEL_PROVIDER={ "name": "redis", "addr": "redis:6379", "user": "changeme", "password": "changeme" }
            # STATEGATE_CHANNEL_PROVIDER={ "name": "nats", "addr": "localhost:4222", "user": "changeme", "password": "changeme" }
            # STATEGATE_CHANNEL_PROVIDER={ "name": "amqp", "addr": "localhost:5672", "user": "changeme", "password": "changeme" }
            - name: STATEGATE_CHANNEL_PROVIDER
              value: '{ "name": "nats", "addr": "nats:4222" }'
            # storage provider configuration(JSON) options: [mongo]
            - name: STATEGATE_STORAGE_PROVIDER
              value: '{ "name": "mongo", "database": "testing", "addr": "mongodb://mongo:27017/testing" }'
            # STATEGATE_CACHE_PROVIDER={ "name": "redis", "addr": "redis:6379", "user": "changeme", "password": "changeme" }
            # STATEGATE_CACHE_PROVIDER={ "name": "memcached", "addr": "localhost:11211" }
            - name: STATEGATE_CACHE_PROVIDER
              value: '{ "name": "redis", "addr": "redis:6379" }'
          image: "stategate/stategate:v0.13.3"
          imagePullPolicy: Always
          ports:
          - containerPort: 8081
          - containerPort: 8080

---
