apiVersion: v1
kind: Namespace
metadata:
  name: eventgate-system
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: eventgate-configmap
data:
  eventgate.yaml: |
    # port to serve on. metrics server is started on this port+1
    server:
      port: 8080
    logging:
      # enable debug logs
      debug: true

    # pluggable backend: [nats]
    backend:
      name: "nats"
      config:
        url: "nats:4444"

    # authentication options
    authentication:
      # json web keys uri for authentication.
      # if empty, inbound jwt's will not be verified.
      jwks_uri: ""

    # authorization options
    authorization:
      requests: |
        package eventgate.authz

        default allow = true
      responses: |
        package eventgate.authz

        default allow = true

---
apiVersion: v1
kind: Service
metadata:
  name: eventgate-service
  namespace: eventgate-system
  labels:
    app: eventgate
spec:
  ports:
  - port: 8080
    name: api
  - port: 8081
    name: metrics
  clusterIP: None
  selector:
    app: eventgate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventgate
  namespace: eventgate-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventgate
  template:
    metadata:
      labels:
        app: eventgate
    spec:
      containers:
        - name: eventgate
          env:
            - name: EVENTGATE_CONFIG
              value: /tmp/eventgate.yaml
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          image: "colemanword/eventgate:v0.0.10"
          imagePullPolicy: Always
          ports:
          - containerPort: 8081
          - containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: "/tmp"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: eventgate-configmap

---
